# Generated by Django 4.1.7 on 2023-04-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogInApp', '0002_rename_useremail_account_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('subTitulo', models.CharField(max_length=256)),
                ('cuerpo', models.CharField(max_length=1024)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogInApp.blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=150)),
                ('commentOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogInApp.blogger')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostsApp.post')),
            ],
        ),
    ]
