# Generated by Django 4.1.7 on 2023-04-06 22:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 19, 1, 52, 534525)),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 19, 1, 52, 533528)),
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
