# Generated by Django 4.1.7 on 2023-04-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userName',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userPassword',
            new_name='userpassword',
        ),
    ]
